/*
* Copyright 2017
* This file is automatically generated by python script
*/

export class Certain{
    public certainType:number;
    public certainId:number;
    public certainValue:number;

    public constructor(data:any){
        this.certainType = data.readInt();
        this.certainId = data.readInt();
        this.certainValue = data.readInt();
    }
}
