import Mark
from ParseXls import ParseXls


class ParseAs(ParseXls):
    def __init__(self, xls_full_path, code_dest_path, cfg_dest_path):
        super(ParseAs, self).__init__(xls_full_path, code_dest_path, cfg_dest_path)

    def _init_type_map(self, mapobj):
        mapobj[Mark.BYTE] = 'int'
        mapobj[Mark.SHORT] = 'int'
        mapobj[Mark.INT] = 'int'
        mapobj[Mark.FLOAT] = 'Number'
        mapobj[Mark.STRING] = 'String'
        #fixme
        # mapobj[Mark.INTARRAY] = 'Array'
        # mapobj[Mark.INTARRAY2] = 'Array'
        # mapobj[Mark.BYTEARRAY] = 'Array'

    def _init_type_fuc_map(self, mapobj):
        mapobj[Mark.BYTE] = 'readUnsignedByte()'
        mapobj[Mark.SHORT] = 'readUnsignedShort()'
        mapobj[Mark.INT] = 'readInt()'
        mapobj[Mark.FLOAT] = 'readFloat()'
        mapobj[Mark.STRING] = 'readUTF()'
        #fixme
        # mapobj[Mark.INTARRAY] = 'readUTF().split("_")'
        # mapobj[Mark.INTARRAY2] = 'readUTF().split(";")'
        # mapobj[Mark.BYTEARRAY] = 'readUTF().split("_")'

    def _get_file_extension_name(self):
        return "as"

    def _get_line_note_mark(self):
        return "//"

    def _get_game_class_templet_str(self):
        return '''/*
* Copyright 2017
* This file is automatically generated by python script
* The data is from @SrTb
*/

package @PkgNm{
    import flash.utils.ByteArray;
    import @PkgNm.@PkgDfNm.*;
    
    public class @ClassNm extends StaticInfoBase{
        @PtDc#public var @PtNm:@PtTp;
        @PtVtDc#public var @PtNm:Vector.<@PtTp>;
        
        public function @ClassNm(data:ByteArray){
            super(data);
            @PrSt#@PtNm = data.@PrFc;
            @MpLnFmBg:@PtNm = [];
            var arr:Array = data.readUTF().split(";");
            var arrLen = arr.length();
            for(var l:int = 0; l<arrLen; ++l){
                @PtNm.push(arr[l].split("_"));
            }@MpLnFmEd#
            @MpLnFmBg:@PtNm = new Vector.<@PtTp>();
            for(var i:int = data.readUnsignedByte(); i>0; --i){
                var child:@PtTp = new @PtTp(data);
                @PtNm.push(child);   
            }@MpLnFmEd#
        }
    }
}
'''

    def _get_define_class_templet_str(self):
        return '''/*
* Copyright 2017
* This file is automatically generated by python script
*/

package @PkgNm.@PkgDfNm{
    import flash.utils.ByteArray;
    
    public class @ClassNm{
        @PtDc#public var @PtNm:@PtTp;
        
        public function @ClassNm(data:ByteArray){
            @PrSt#@PtNm = data.@PrFc;
        }
    }
}
'''
