# @...# mean a list
MARK_PACKAGE = '@PkgNm'
MARK_PACKAGE_DEFINE = '@PkgDfNm'
MARK_CLASS_NAME = '@ClassNm'
MARK_SUPER_CLASS_NAME = '@SClassNm'
MARK_PROPERTY_NAME = '@PtNm'
MARK_PROPERTY_TYPE = '@PtTp'
MARK_PROPERTY_DECLARE_LIST = '@PtDc#'
MARK_CLASS_DECLARE_LIST = '@ClDc#'
MARK_VECTOR_DECLARE_MODE = '@VtDc'
MARK_PARSE_SENTENCE_LIST = '@PrSt#'
MARK_PARSE_FUNCTION_NAME = '@PrFc'
MARK_TEMP_LIST_VAR = '@TpLv#'

MARK_MULTIPLE_LINE_FORMAT_BEGIN = '@MpLnFmBg:'
MARK_MULTIPLE_LINE_FORMAT_END = '@MpLnFmEd#'

MARK_ES_IMPORT_DECLARE_LIST = '@EsIpDc#'
MARK_ES_EXPORT_DECLARE_LIST = '@EsEpDc#'

MARK_SOURCE_TABLE = '@SrTb'

PATH_CONFIG_PACKAGE = 'dat'
PATH_PACKAGE = 'staticdata'
PATH_PACKAGE_DEFINE = 'define'

BYTE = 'byte'
SHORT = 'short'
INT = 'int'
FLOAT = 'float'
STRING = 'string'
