import Mark
from ParseXls import ParseXls


class ParseTs(ParseXls):
    def _init_type_map(self, map_obj):
        map_obj[Mark.BYTE] = 'number'
        map_obj[Mark.SHORT] = 'number'
        map_obj[Mark.INT] = 'number'
        map_obj[Mark.FLOAT] = 'number'
        map_obj[Mark.STRING] = 'string'

    def _init_type_fuc_map(self, map_obj):
        map_obj[Mark.BYTE] = 'readUnsignedByte()'
        map_obj[Mark.SHORT] = 'readUnsignedShort()'
        map_obj[Mark.INT] = 'readInt()'
        map_obj[Mark.FLOAT] = 'readFloat()'
        map_obj[Mark.STRING] = 'readUTF()'

    def _get_file_extension_name(self):
        return "ts"

    def _get_line_note_mark(self):
        return "//"

    def _get_game_class_templet_str(self):
        return '''/*
* Copyright 2017
* This file is automatically generated by python script
* The data is from @SrTb
*/

namespace @PkgNm{
    export class @ClassNm{
        @PtDc#
        public @PtNm:@PtTp;@VtDc@PtTp[]

        public constructor(data:any){
            @PrSt#
            this.@PtNm = data.@PrFc;
            @MpLnFmBg:this.@PtNm = [];
            for(let i = data.readUnsignedByte()-1; i>=0; --i){
                let child:@PtTp = new @PtTp(data);
                this.@PtNm.push(child);
            }@MpLnFmEd#
            @MpLnFmBg:this.@PtNm = [];
            for(let i = data.readUnsignedByte()-1; i>=0; --i){
                this.@PtNm.push(data.@PrFc);
            }@MpLnFmEd#
            @MpLnFmBg:this.@PtNm = [];
            for(let i = data.readUnsignedByte()-1; i>=0; --i){
                let tempList = [];
                this.@PtNm.push(tempList);
                for(let j = data.readUnsignedByte()-1; j>=0; --j){
                    tempList.push(data.@PrFc);
                }
            }@MpLnFmEd#
        }
    }
}
'''

    def _get_define_class_templet_str(self):
        return '''/*
* Copyright 2017
* This file is automatically generated by python script
*/

namespace @PkgNm{
    export class @ClassNm{
        @PtDc#
        public @PtNm:@PtTp;

        public constructor(data:any){
            @PrSt#
            this.@PtNm = data.@PrFc;
        }
    }
}
'''

    def _get_class_collection_templet_str(self):
        return '''/*
* Copyright 2017
* This file is automatically generated by python script
*/

@EsIpDc#
///<reference path="@ClassNm.ts"/>

namespace @PkgNm{
    export class @ClassNm{
        @PtDc#
        public static map@ClassNm:Map<number, @ClassNm> = new Map<number, @ClassNm>();
    }

    @EsEpDc#
    export function static@PtTp(value:number):@PtTp{ return @ClassNm.map@PtTp.get(value);}
}

'''
