import Mark
from ParseXls import ParseXls


class ParseTs(ParseXls):
    def __init__(self, xls_full_path, code_dest_path, cfg_dest_path):
        super(ParseTs, self).__init__(xls_full_path, code_dest_path, cfg_dest_path)

    def _init_type_map(self, mapobj):
        mapobj[Mark.BYTE] = 'number'
        mapobj[Mark.SHORT] = 'number'
        mapobj[Mark.INT] = 'number'
        mapobj[Mark.FLOAT] = 'number'
        mapobj[Mark.STRING] = 'string'

    def _init_type_fuc_map(self, mapobj):
        mapobj[Mark.BYTE] = 'readUnsignedByte()'
        mapobj[Mark.SHORT] = 'readUnsignedShort()'
        mapobj[Mark.INT] = 'readInt()'
        mapobj[Mark.FLOAT] = 'readFloat()'
        mapobj[Mark.STRING] = 'readUTF()'

    def _get_file_extension_name(self):
        return "ts"

    def _get_line_note_mark(self):
        return "//"

    def _get_game_class_templet_str(self):
        return '''///<reference path="../StaticInfoBase.ts"/>
/*
* Copyright 2017
* This file is automatically generated by python script
* The data is from @SrTb
*/

namespace @PkgNm{
    import ByteArray = egret.ByteArray;
    
    export class @ClassNm extends StaticInfoBase{
        @PtDc#public @PtNm:@PtTp;
        @VtDc@PtNm[]
        
        public constructor(data:ByteArray){
            super(data);
            @TpLv# let tempList;
            @PrSt#this.@PtNm = data.@PrFc;
            @MpLnFmBg:this.@PtNm = [];
            for(let i = data.readUnsignedByte()-1; i>=0; --i){
                let child:@PtTp = new @PtTp(data);
                this.@PtNm.push(child);
            }@MpLnFmEd#
            @MpLnFmBg:this.@PtNm = [];
            for(let i = data.readUnsignedByte()-1; i>=0; --i){
                this.@PtNm.push(data.@PrFc);
            }@MpLnFmEd#
            @MpLnFmBg:this.@PtNm = [];
            for(let i = data.readUnsignedByte()-1; i>=0; --i){
                let tempList = [];
                this.@PtNm.push(tempList);
                for(let j = data.readUnsignedByte()-1; j>=0; --j){
                    tempList.push(data.@PrFc);
                }
            }@MpLnFmEd#
        }
    }
}
'''

    def _get_define_class_templet_str(self):
        return '''/*
* Copyright 2017
* This file is automatically generated by python script
*/

namespace @PkgNm{
    import ByteArray = egret.ByteArray;
    
    export class @ClassNm{
        @PtDc#public @PtNm:@PtTp;
        
        public constructor(data:ByteArray){
            @PrSt#this.@PtNm = data.@PrFc;
        }
    }
}
'''
