/*
* Copyright 2017
* This file is automatically generated by python script
*/

import { TestUnit } from "./TestUnit";

export class StaticData{
    public static TestUnit = TestUnit;

    public static mapTestUnit:Map<number, TestUnit> = new Map<number, TestUnit>();
}

export function staticTestUnit(value:number):TestUnit{ return StaticData.mapTestUnit.get(value);}
